import tensorflow as tf
import tflowtools as TFT

########CONFIG########

YEAST_CONFIG = {
	'name': "yeast",
	'steps': 53000,
	'lrate': "scale",
	'tint': 100,
	'showint': 1000,
	'mbs': 53,
	'wgt_range': (-.3,.3),
	'hidden_layers':[50,50],
	'hidac': (lambda x, y: tf.tanh(x,name=y)),
	'outac': (lambda x, y: tf.nn.softmax(x,name=y)),
	'case_generator': "yeast.txt",
	'stdeviation': True,
	'vfrac': 0.1 ,
	'tfrac': 0.1,
	'cfunc': 'rmse',
	'mapbs': 0,
	'cfrac':1.0,
	'map_layers': [],
	'display_wgts': [],
	'display_biases': [],
	'dendrogram_layers': [],
	'numeric': False
}

WINE_CONFIG = {
	'name': "wine",
	'steps': 41000,
	'lrate': "scale",
	'tint': 100,
	'showint': 1000,
	'mbs': 41,
	'wgt_range': (-.3,.3),
	'hidden_layers':[50,50],
	'hidac': (lambda x, y: tf.tanh(x,name=y)),
	'outac': (lambda x, y: tf.nn.softmax(x,name=y)),
	'case_generator': "winequality_red.txt",
	'stdeviation': True,
	'vfrac': 0.1 ,
	'tfrac': 0.1,
	'cfunc': 'rmse',
	'mapbs': 0,
	'cfrac':1.0,
	'map_layers': [],
	'display_wgts': [],
	'display_biases': [],
	'dendrogram_layers': [],
	'numeric': False
}

GLASS_CONFIG = {
	'name': "glass",
	'steps': 107000,
	'lrate': "scale",
	'tint': 100,
	'showint': 1000,
	'mbs': 107,
	'wgt_range': (-.3,.3),
	'hidden_layers':[50,50],
	'hidac': (lambda x, y: tf.tanh(x,name=y)),
	'outac': (lambda x, y: tf.nn.softmax(x,name=y)),
	'case_generator': "glass.txt",
	'stdeviation': True,
	'vfrac': 0.1 ,
	'tfrac': 0.1,
	'cfunc': 'rmse',
	'mapbs': 0,
	'cfrac':1.0,
	'map_layers': [],
	'display_wgts': [],
	'display_biases': [],
	'dendrogram_layers': [],
	'numeric': False
}

MNIST_CONFIG = {
	'name': "mnist",
	'steps': 60000,
	'lrate': "scale",
	'tint': 10,
	'showint': 1000,
	'mbs': 300,
	'wgt_range': (-.3,.3),
	'hidden_layers':[50,50],
	'hidac': (lambda x, y: tf.tanh(x,name=y)),
	'outac': (lambda x, y: tf.nn.softmax(x,name=y)),
	'case_generator': "mnist.txt",
	'stdeviation': False,
	'vfrac': 0.1 ,
	'tfrac': 0.1,
	'cfunc': 'rmse',
	'mapbs': 0,
	'cfrac':1.0,
	'map_layers': [],
	'display_wgts': [],
	'display_biases': [],
	'dendrogram_layers': [],
	'numeric': False
}

IRIS_CONFIG = {
	'name': "iris",
	'steps': 50000,
	'lrate': "scale",
	'tint': 100,
	'showint': 1000,
	'mbs': 50,
	'wgt_range': (-.3,.3),
	'hidden_layers':[50,50],
	'hidac': (lambda x, y: tf.tanh(x,name=y)),
	'outac': (lambda x, y: tf.nn.softmax(x,name=y)),
	'case_generator': "iris.txt",
	'stdeviation': True,
	'vfrac': 0.1 ,
	'tfrac': 0.1,
	'cfunc': 'rmse',
	'mapbs': 0,
	'cfrac':1.0,
	'map_layers': [],
	'display_wgts': [],
	'display_biases': [],
	'dendrogram_layers': [],
	'numeric': False
}

PARITY_CONFIG = {
	'name': "parity",
	'steps': 1024000,
	'lrate': "scale",
	'tint': 100,
	'showint': 100,
	'mbs': 1024,
	'wgt_range': (-1,1),
	'hidden_layers':[50,50],
	'hidac': (lambda x, y: tf.tanh(x,name=y)),
	'outac': (lambda x, y: tf.nn.softmax(x,name=y)),
	'case_generator': (lambda: TFT.gen_all_parity_cases(10)),
	'stdeviation': False,
	'vfrac': 0.1 ,
	'tfrac': 0.1,
	'cfunc': 'rmse',
	'mapbs': 0,
	'cfrac':1.0,
	'map_layers': [],
	'display_wgts': [],
	'display_biases': [],
	'dendrogram_layers': [],
	'numeric': False
}

SEGCOUNTER_CONFIG = {
	'name': "segcounter",
	'steps': 100000,
	'lrate': "scale",
	'tint': 100,
	'showint': 100,
	'mbs': 100,
	'wgt_range': (-.3,.3),
	'hidden_layers':[50,50],
	'hidac': (lambda x, y: tf.tanh(x,name=y)),
	'outac': (lambda x, y: tf.nn.softmax(x,name=y)),
	'case_generator': (lambda: TFT.gen_segmented_vector_cases(25,1000,0,8)),
	'stdeviation': False,
	'vfrac': 0.1 ,
	'tfrac': 0.1,
	'cfunc': 'rmse',
	'mapbs': 0,
	'cfrac':1.0,
	'map_layers': [],
	'display_wgts': [],
	'display_biases': [],
	'dendrogram_layers': [],
	'numeric': False
}

BITCOUNTER_CONFIG = {
	'name': "bitcounter",
	'steps': 200000,
	'lrate': "scale",
	'tint': 100,
	'showint': 100,
	'mbs': 50,
	'wgt_range': (-.1,.1),
	'hidden_layers':[50,50],
	'hidac': (lambda x, y: tf.tanh(x,name=y)),
	'outac': (lambda x, y: tf.nn.softmax(x,name=y)),
	'case_generator': (lambda: TFT.gen_vector_count_cases(500,15)),
	'stdeviation': False,
	'vfrac': 0.1 ,
	'tfrac': 0.1,
	'cfunc': 'rmse',
	'mapbs': 0,
	'cfrac':1.0,
	'map_layers': [],
	'display_wgts': [],
	'display_biases': [],
	'dendrogram_layers': [],
	'numeric': False
}

AUTOENCODER_CONFIG = {
	'name': "autoencoder",
	'steps': 30000,
	'lrate': "scale",
	'tint': 100,
	'showint': 100,
	'mbs': 100,
	'wgt_range': (-.3,.3),
	'hidden_layers':[4],
	'hidac': (lambda x, y: tf.tanh(x,name=y)),
	'outac': (lambda x, y: tf.nn.softmax(x,name=y)),
	'case_generator': (lambda: TFT.gen_all_one_hot_cases(3)),
	'stdeviation': False,
	'vfrac': 0.0 ,
	'tfrac': 0.0,
	'cfunc': 'rmse',
	'mapbs': 3,
	'cfrac':1.0,
	'map_layers': [0,1,2],
	'display_wgts': [1,2],
	'display_biases': [1,2],
	'dendrogram_layers': [1],
	'numeric': False
}






